# Travis build integration.
# https://docs.travis-ci.com/

language: c
dist: focal
os: linux
osx_image: xcode11.3.1

jobs:
  include:
    - compiler: gcc
      arch: amd64
    - compiler: gcc
      arch: arm64
    - compiler: gcc
      arch: ppc64le
    - compiler: gcc
      arch: s390x
    - compiler: clang
      arch: amd64
    - compiler: coverity
      arch: amd64
      env:
        - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
        - COVERITY_SCAN_BRANCH_PATTERN="master"
        - COVERITY_SCAN_NOTIFICATION_EMAIL="grobian@gentoo.org"
        - COVERITY_SCAN_BUILD_COMMAND="make"
    - compiler: valgrind
      arch: amd64
      env:
        - CFLAGS="-g"
        - Q_RUN_WITH_VALGRIND=1
    - compiler: clang
      os: osx
      env:
        - LDFLAGS="-L/usr/local/opt/libressl/lib"
        - CPPFLAGS="-I/usr/local/opt/libressl/include"
        - PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"
        - PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"

env:
  global:
    - secure: "qF/ueXvm1uawirfQL+jK5LSJW1P+ZVXDx5t9HljFP1jC45D/1aqEs1ffaNkvBJohUJy6mABnXN5+ZP0PoQ+ZA01t+6NDc/LrowGP87T02KGwjBukQ9tQK8zVutsT+0CY3qUPhRcaLH5Gt3c+uPDKlLndg/bXWS6cRpMt6tC3VTy+WpAlvHHfZJjSZVYp8qhCattnaZ7GvzqGqbjBZ6X7TrQnwIDdGAyg5r4xnViDxu9lO4ZH4zS6Rc7DxesrqC3zxwPRw5HLNsGbJiGQF3meXH6rVNt1uxKwwOQoDcL0NKiyAMpXwu5iGeuMILoy3KMpFwZFnhyXqMGRORakDuDNB9oMgzp+PB3Zb7TICXbhxbrQ46lSlv0VWkwn3bcJ0lek53NzDUmM2uywvCUYybPgn3xCqY9jG0zwO2ZIACc1ekGh7y0gFXfBoSZGhl1VthV5hWMJ01p/n5jK7XdDmK4G/+0wN2WlHhyvjoF6XyJ+SRC85l6VhpBNbFJA2bGT2Y4+p/CzF7M8DVYR3o+OfCWxsiZyE+Vnmpdg4U829oy97obIuBeCvBd1Vp0hoB+RpzaeqzS69N+S4tgCIXvIdu168HltFaTUPtvIGoDtIAPCaUZC8jVO22cA6RpNkac3HjpLSceYYtdkiph4VuBMwHZj6/N2+m46Y9Uxrh01KzLy/GY="

addons:
  apt:
    packages:
    - libgpgme11-dev
    - gnupg2
    - valgrind
    - liblz4-tool
    - lzop
    - zstd
    - lzip
    - brotli
  homebrew:
    packages:
    - gpgme
    - gnupg
    - gnu-sed
    - coreutils
    - bash
    - libressl

before_install:
  - ./travis/install-blake2.sh
script: ./travis/main.sh
